baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme1 = "ananke"
theme = "nia"


summaryLength = 3

[menu]
    [[menu.main]]
        name="Блог"
        url="/posts"
        weight = 1
    [[menu.main]]
        name="About"
        url="/about"
        weight = 4
    [[menu.main]]
        name="tags"
        url="/tags"
        weight = 5
    [[menu.main]]
        name="categories"
        url="/categories"
        weight = 6


[taxonomies]
  category = "categories"
  tag = "tags"